/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogGestionContacts.java
 *
 * Created on 23 janv. 2010, 16:56:22
 */

package fr.alma.gtd.ihm;

import fr.alma.gtd.entities.Contact;
import fr.alma.gtd.ihm.renseignement.DialogAjoutContact;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Le_Clubber
 */
public class DialogGestionContacts extends javax.swing.JDialog {

	private DefaultListModel listeDisponibleModel;

    /** Creates new form DialogGestionContacts */
    public DialogGestionContacts(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
		listeDisponibleModel = new DefaultListModel();
        initComponents();
		initialisation();
		setLocationRelativeTo(null);

		// apparence selon le systeme
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
			javax.swing.SwingUtilities.updateComponentTreeUI(this);
		} catch (Exception e) {
			System.out.println("LookAndFeel non supporté.");
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textTelephone = new javax.swing.JTextField();
        textEMail = new javax.swing.JTextField();
        textAdresse = new javax.swing.JTextField();
        textPrenom = new javax.swing.JTextField();
        textNom = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listContacts = new javax.swing.JList(listeDisponibleModel);
        ok = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations du contact"));

        jLabel1.setText("Nom :");

        jLabel2.setText("Prenom :");

        jLabel3.setText("Adresse :");

        jLabel4.setText("E-mail :");

        jLabel5.setText("Téléphone :");

        textTelephone.setEditable(false);

        textEMail.setEditable(false);

        textAdresse.setEditable(false);

        textPrenom.setEditable(false);

        textNom.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(textNom, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(15, 15, 15)
                        .addComponent(textAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(textEMail, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des contacts"));

        listContacts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listContacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listContactsMouseClicked(evt);
            }
        });
        listContacts.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listContactsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listContacts);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel2);

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        ajouter.setText("Ajouter un contact");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(ok)
                .addContainerGap())
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(ajouter))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
		Contact contact = new DialogAjoutContact(null, true).showDialog();
		if (contact != null) {
			controleur.ajoutContact(contact);
			listeDisponibleModel.addElement(contact);
		}
	}//GEN-LAST:event_ajouterActionPerformed

	private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
		setVisible(false);
	}//GEN-LAST:event_okActionPerformed

	private void listContactsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listContactsValueChanged
		int indice = listContacts.getLeadSelectionIndex();
		if (indice >= 0) {
			Contact c = (Contact) listeDisponibleModel.get(indice);
			textNom.setText(c.getNom());
			textPrenom.setText(c.getPrenom());
			textAdresse.setText(c.getAdresse());
			textEMail.setText(c.getEmail());
			textTelephone.setText(c.getTelephone());
		} else {
			textNom.setText(null);
			textPrenom.setText(null);
			textAdresse.setText(null);
			textEMail.setText(null);
			textTelephone.setText(null);
		}
	}//GEN-LAST:event_listContactsValueChanged

	private void listContactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listContactsMouseClicked
		if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
			int index = listContacts.locationToIndex(evt.getPoint());
			if (index != -1) {
				listContacts.setSelectedIndex(index);
				javax.swing.JPopupMenu jpm = new javax.swing.JPopupMenu();
				javax.swing.JMenuItem modifMenu = new javax.swing.JMenuItem("Modifier le contact");
				modifMenu.addActionListener(new ListModifMenuListener(listContacts.getSelectedValue()));
				jpm.add(modifMenu);
				javax.swing.JMenuItem eraseMenu = new javax.swing.JMenuItem("Effacer le contact");
				eraseMenu.addActionListener(new ListEraseMenuListener(listContacts.getSelectedValue()));
				jpm.add(eraseMenu);
				jpm.show(listContacts, evt.getX(), evt.getY());
			}
		}
	}//GEN-LAST:event_listContactsMouseClicked

	class ListEraseMenuListener implements java.awt.event.ActionListener{
		private Object object;
		public ListEraseMenuListener(Object obj){
			this.object = obj;
		}
		@Override
		public void actionPerformed(java.awt.event.ActionEvent e) {
			controleur.supprimerContact(object);
			listeDisponibleModel.removeElement(object);
		}
	}

	class ListModifMenuListener implements java.awt.event.ActionListener{
		private Contact contact;
		public ListModifMenuListener(Object obj){
			this.contact = (Contact) obj;
		}
		@Override
		public void actionPerformed(java.awt.event.ActionEvent e) {
			DialogAjoutContact dialog = new DialogAjoutContact(null, true);
			dialog.setInfos(contact);
			Contact temp = dialog.showDialog();
			if (temp != null) {
				contact.setNom(temp.getNom());
				contact.setPrenom(temp.getPrenom());
				contact.setAdresse(temp.getAdresse());
				contact.setEmail(temp.getEmail());
				contact.setTelephone(temp.getTelephone());
				controleur.actualiserContact(contact);
				listContactsValueChanged(null);
			}
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList listContacts;
    private javax.swing.JButton ok;
    private javax.swing.JTextField textAdresse;
    private javax.swing.JTextField textEMail;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textPrenom;
    private javax.swing.JTextField textTelephone;
    // End of variables declaration//GEN-END:variables

	private Controleur controleur;

	private void initialisation() {
		controleur = Controleur.getInstance();
		List<Contact> listeContactsDisponible = controleur.getListeContacts();
		for (Contact c : listeContactsDisponible) {
			listeDisponibleModel.addElement(c);
		}
	}

}
