/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelChoseAFaire.java
 *
 * Created on 12 janv. 2010, 21:31:10
 */

package fr.alma.gtd.ihm;

import javax.swing.DefaultListModel;

/**
 *
 * @author Le_Clubber
 */
public class PanelChosesAFaire extends javax.swing.JPanel {

	private Controleur controleur;
    private DefaultListModel listeChoseAFaire;

    /** Creates new form PanelChoseAFaire */
    public PanelChosesAFaire() {
		this.listeChoseAFaire = new DefaultListModel();
        initComponents();
		this.controleur = Controleur.getInstance();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        listeCAF = new javax.swing.JList(listeChoseAFaire);
        jLabel1 = new javax.swing.JLabel();

        listeCAF.setEnabled(false);
        listeCAF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listeCAFMousePressed(evt);
            }
        });
        jScrollPane.setViewportView(listeCAF);

        jLabel1.setText("Liste des choses à réaliser \"un jour\" :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listeCAFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeCAFMousePressed
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON3){
			int index = listeCAF.locationToIndex(evt.getPoint());
			if (index != -1) {
				listeCAF.setSelectedIndex(index);
				javax.swing.JPopupMenu jpm = new javax.swing.JPopupMenu();
				javax.swing.JMenuItem aTraiterMenu = new javax.swing.JMenuItem("Définir comme à traiter");
				aTraiterMenu.addActionListener(new ListATraiterMenuListener(listeCAF.getSelectedValue()));
				jpm.add(aTraiterMenu);
				javax.swing.JMenuItem eraseMenu = new javax.swing.JMenuItem("Effacer la chose à faire");
				eraseMenu.addActionListener(new ListEraseMenuListener(listeCAF.getSelectedValue()));
				jpm.add(eraseMenu);
				jpm.show(listeCAF, evt.getX(), evt.getY());
			}
		}
    }//GEN-LAST:event_listeCAFMousePressed

	class ListEraseMenuListener implements java.awt.event.ActionListener{
		private Object object;
		public ListEraseMenuListener(Object obj){
			this.object = obj;
		}
		@Override
		public void actionPerformed(java.awt.event.ActionEvent e) {
			controleur.supprimerCAF(object);
		}
	}

	class ListATraiterMenuListener implements java.awt.event.ActionListener{
		private Object object;
		public ListATraiterMenuListener(Object obj){
			this.object = obj;
		}
		@Override
		public void actionPerformed(java.awt.event.ActionEvent e) {
			controleur.aTraiter(object);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JList listeCAF;
    // End of variables declaration//GEN-END:variables

	public void compteCharge(boolean estCharge) {
		listeCAF.setEnabled(estCharge);
	}

	public void actaliser() {
		listeChoseAFaire.clear();
		controleur.constructionListeChoseAFaireUnJour(listeChoseAFaire);
		listeCAF.setSelectedIndex(listeCAF.getFirstVisibleIndex());
	}

}
