/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Connection.java
 *
 * Created on 5 janv. 2010, 05:34:03
 */

package fr.alma.gtd.ihm.gestionComptes;

/**
 *
 * @author E023963X
 */
public class ChargementCompte extends javax.swing.JDialog {

    /** Creates new form Connection */
    public ChargementCompte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
		setLocationRelativeTo(null);
        initComponents();

		// apparence selon le systeme
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
			javax.swing.SwingUtilities.updateComponentTreeUI(this);
		} catch (Exception e) {
			System.out.println("LookAndFeel non supporté.");
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        mdpLabel = new javax.swing.JLabel();
        loginText = new javax.swing.JTextField();
        annulerBotton = new javax.swing.JButton();
        chargerButton = new javax.swing.JButton();
        mdpText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        loginLabel.setText("Login :");

        mdpLabel.setText("Mot de passe :");

        loginText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                loginTextCaretUpdate();
            }
        });
        loginText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextActionPerformed();
            }
        });

        annulerBotton.setText("Annuler");
        annulerBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerBottonActionPerformed();
            }
        });

        chargerButton.setText("Charger");
        chargerButton.setEnabled(false);
        chargerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargerButtonActionPerformed();
            }
        });

        mdpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdpTextActionPerformed();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mdpLabel)
                            .addComponent(loginLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mdpText, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(loginText, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chargerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annulerBotton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mdpLabel)
                    .addComponent(mdpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulerBotton)
                    .addComponent(chargerButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void annulerBottonActionPerformed() {//GEN-FIRST:event_annulerBottonActionPerformed
		loginInfo.setAnnule(true);
		setVisible(false);
	}//GEN-LAST:event_annulerBottonActionPerformed

	private void chargerButtonActionPerformed() {//GEN-FIRST:event_chargerButtonActionPerformed
		loginInfo = new LoginInfo(loginText.getText(), mdpText.getText());
		setVisible(false);
	}//GEN-LAST:event_chargerButtonActionPerformed

	private void loginTextActionPerformed() {//GEN-FIRST:event_loginTextActionPerformed
		this.chargerButtonActionPerformed();
	}//GEN-LAST:event_loginTextActionPerformed

	private void loginTextCaretUpdate() {//GEN-FIRST:event_loginTextCaretUpdate
		this.chargerButton.setEnabled(this.loginText.getText().length() > 0);
	}//GEN-LAST:event_loginTextCaretUpdate

	private void mdpTextActionPerformed() {//GEN-FIRST:event_mdpTextActionPerformed
		this.chargerButtonActionPerformed();
	}//GEN-LAST:event_mdpTextActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        ChargementCompte fenetre = new ChargementCompte(null, true);
		LoginInfo infos = fenetre.showDialog();
		System.out.println(infos.getLogin());
		System.out.println(infos.getMdp());
		System.out.println(infos.getMdpConfirme());
		System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerBotton;
    private javax.swing.JButton chargerButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginText;
    private javax.swing.JLabel mdpLabel;
    private javax.swing.JPasswordField mdpText;
    // End of variables declaration//GEN-END:variables

	private LoginInfo loginInfo;

	public LoginInfo showDialog(){
		this.loginInfo = new LoginInfo();
		this.setVisible(true);
		return this.loginInfo;
	}

}
