/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NouveauCompte.java
 *
 * Created on 5 janv. 2010, 05:47:29
 */

package fr.alma.gtd.ihm.gestionComptes;

/**
 *
 * @author E023963X
 */
public class NouveauCompte extends javax.swing.JDialog {

    /** Creates new form NouveauCompte */
    public NouveauCompte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
		setLocationRelativeTo(null);
        initComponents();

		// apparence selon le systeme
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
			javax.swing.SwingUtilities.updateComponentTreeUI(this);
		} catch (Exception e) {
			System.out.println("LookAndFeel non supporté.");
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        mdpLabel = new javax.swing.JLabel();
        mdpConfirmationLabel = new javax.swing.JLabel();
        mdpConfirmationText = new javax.swing.JPasswordField();
        mdpText = new javax.swing.JPasswordField();
        loginText = new javax.swing.JTextField();
        annulerButton = new javax.swing.JButton();
        validerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        loginLabel.setText("Login :");

        mdpLabel.setText("Entrez le mot de passe :");

        mdpConfirmationLabel.setText("Confirmez le mot de passe :");

        mdpConfirmationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdpConfirmationTextActionPerformed(evt);
            }
        });

        mdpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdpTextActionPerformed(evt);
            }
        });

        loginText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                loginTextCaretUpdate(evt);
            }
        });
        loginText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextActionPerformed(evt);
            }
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        validerButton.setText("Valider");
        validerButton.setEnabled(false);
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginText, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mdpConfirmationLabel)
                            .addComponent(mdpLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mdpText, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(mdpConfirmationText, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(validerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annulerButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mdpLabel)
                    .addComponent(mdpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mdpConfirmationLabel)
                    .addComponent(mdpConfirmationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulerButton)
                    .addComponent(validerButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
		loginInfo = new LoginInfo(loginText.getText(), mdpText.getText(), mdpConfirmationText.getText());
		setVisible(false);
	}//GEN-LAST:event_validerButtonActionPerformed

	private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
		loginInfo.setAnnule(true);
		setVisible(false);
	}//GEN-LAST:event_annulerButtonActionPerformed

	private void loginTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextActionPerformed
		this.validerButtonActionPerformed(evt);
	}//GEN-LAST:event_loginTextActionPerformed

	private void loginTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_loginTextCaretUpdate
		this.validerButton.setEnabled(this.loginText.getText().length() > 0);
	}//GEN-LAST:event_loginTextCaretUpdate

	private void mdpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdpTextActionPerformed
		this.validerButtonActionPerformed(evt);
	}//GEN-LAST:event_mdpTextActionPerformed

	private void mdpConfirmationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdpConfirmationTextActionPerformed
		this.validerButtonActionPerformed(evt);
	}//GEN-LAST:event_mdpConfirmationTextActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        NouveauCompte fenetre = new NouveauCompte(null, true);
		LoginInfo infos = fenetre.showDialog();
		System.out.println(infos.getLogin());
		System.out.println(infos.getMdp());
		System.out.println(infos.getMdpConfirme());
		System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginText;
    private javax.swing.JLabel mdpConfirmationLabel;
    private javax.swing.JPasswordField mdpConfirmationText;
    private javax.swing.JLabel mdpLabel;
    private javax.swing.JPasswordField mdpText;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables

	private LoginInfo loginInfo;
	
	public LoginInfo showDialog(){
		this.loginInfo = new LoginInfo();
		this.setVisible(true);		
		return this.loginInfo;		
	}

}
