package donneespartagees.CallbackPackage;


/**
 * donneespartagees/CallbackPackage/UneErreur.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */

public final class UneErreur extends org.omg.CORBA.UserException
{
	private static final long serialVersionUID = 4166506552299504808L;
	public String message = null;
	public short ligne = (short)0;

	public UneErreur ()
	{
		super(UneErreurHelper.id());
	} // ctor

	public UneErreur (String _message, short _ligne)
	{
		super(UneErreurHelper.id());
		message = _message;
		ligne = _ligne;
	} // ctor


	public UneErreur (String $reason, String _message, short _ligne)
	{
		super(UneErreurHelper.id() + "  " + $reason);
		message = _message;
		ligne = _ligne;
	} // ctor

} // class UneErreur
