/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogAjoutContact.java
 *
 * Created on 18 janv. 2010, 23:00:52
 */

package fr.alma.gtd.ihm.renseignement;

import fr.alma.gtd.entities.Contact;

/**
 *
 * @author Le_Clubber
 */
public class DialogAjoutContact extends javax.swing.JDialog {

    /** Creates new form DialogAjoutContact */
    public DialogAjoutContact(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
		setLocationRelativeTo(null);
        initComponents();

		// apparence selon le systeme
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
			javax.swing.SwingUtilities.updateComponentTreeUI(this);
		} catch (Exception e) {
			System.out.println("LookAndFeel non supporté.");
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        adresse = new javax.swing.JLabel();
        eMail = new javax.swing.JLabel();
        telephone = new javax.swing.JLabel();
        textTelephone = new javax.swing.JTextField();
        textEMail = new javax.swing.JTextField();
        textAdresse = new javax.swing.JTextField();
        textPrenom = new javax.swing.JTextField();
        textNom = new javax.swing.JTextField();
        annuler = new javax.swing.JButton();
        valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nom.setText("Nom :");

        prenom.setText("Prénom :");

        adresse.setText("Adresse :");

        eMail.setText("E-mail :");

        telephone.setText("Téléphone :");

        textPrenom.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textPrenomCaretUpdate();
            }
        });

        textNom.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textNomCaretUpdate();
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed();
            }
        });

        valider.setText("Valider");
        valider.setEnabled(false);
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(valider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annuler))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephone)
                            .addComponent(eMail)
                            .addComponent(nom)
                            .addComponent(prenom)
                            .addComponent(adresse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(textPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(textEMail, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(textTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(textNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenom)
                    .addComponent(textPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresse)
                    .addComponent(textAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMail)
                    .addComponent(textEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephone)
                    .addComponent(textTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annuler)
                    .addComponent(valider))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void annulerActionPerformed() {//GEN-FIRST:event_annulerActionPerformed
		setVisible(false);
	}//GEN-LAST:event_annulerActionPerformed

	private void validerActionPerformed() {//GEN-FIRST:event_validerActionPerformed
		this.infos = new Contact(textNom.getText(), textPrenom.getText());
		this.infos.setAdresse(textAdresse.getText());
		this.infos.setEmail(textEMail.getText());
		this.infos.setTelephone(textTelephone.getText());
		setVisible(false);
	}//GEN-LAST:event_validerActionPerformed

	private void textNomCaretUpdate() {//GEN-FIRST:event_textNomCaretUpdate
		activerValider();
	}//GEN-LAST:event_textNomCaretUpdate

	private void textPrenomCaretUpdate() {//GEN-FIRST:event_textPrenomCaretUpdate
		activerValider();
	}//GEN-LAST:event_textPrenomCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresse;
    private javax.swing.JButton annuler;
    private javax.swing.JLabel eMail;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel telephone;
    private javax.swing.JTextField textAdresse;
    private javax.swing.JTextField textEMail;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textPrenom;
    private javax.swing.JTextField textTelephone;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables

	private void activerValider() {
		valider.setEnabled(textNom.getText().length() + textPrenom.getText().length() > 0);
	}
	
	private Contact infos;

	public Contact showDialog() {
		this.infos = null;
		this.setVisible(true);
		return this.infos;
	}

	public void setInfos(Contact contact) {
		textNom.setText(contact.getNom());
		textPrenom.setText(contact.getPrenom());
		textAdresse.setText(contact.getAdresse());
		textEMail.setText(contact.getEmail());
		textTelephone.setText(contact.getTelephone());
	}

}
