/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogContact.java
 *
 * Created on 18 janv. 2010, 22:42:02
 */

package fr.alma.gtd.ihm.renseignement;

import fr.alma.gtd.entities.Contact;
import fr.alma.gtd.ihm.Controleur;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Le_Clubber
 */
public class DialogContact extends javax.swing.JDialog {

	private DefaultListModel listeDisponibleModel;
	private DefaultListModel listeAjouteeModel;

    /** Creates new form DialogContact */
    public DialogContact(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
		setLocationRelativeTo(null);
		listeDisponibleModel = new DefaultListModel();
		listeAjouteeModel = new DefaultListModel();
        initComponents();

		// apparence selon le systeme
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
			javax.swing.SwingUtilities.updateComponentTreeUI(this);
		} catch (Exception e) {
			System.out.println("LookAndFeel non supporté.");
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valider = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listExistant = new javax.swing.JList(listeDisponibleModel);
        ajouterBouton = new javax.swing.JButton();
        retirerBouton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAjoutee = new javax.swing.JList(listeAjouteeModel);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        creerContact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listExistant);

        ajouterBouton.setText(">");
        ajouterBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBoutonActionPerformed(evt);
            }
        });

        retirerBouton.setText("<");
        retirerBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerBoutonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listAjoutee);

        jLabel1.setText("Contacts disponibles :");

        jLabel2.setText("Contacts ajoutés :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retirerBouton)
                            .addComponent(ajouterBouton)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ajouterBouton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retirerBouton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addContainerGap())
        );

        creerContact.setText("Ajouter un contact");
        creerContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creerContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(valider)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creerContact)
                    .addComponent(valider))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
		setVisible(false);
	}//GEN-LAST:event_validerActionPerformed

	private void creerContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerContactActionPerformed
		Contact contact = new DialogAjoutContact(null, true).showDialog();
		if (contact != null) {
			controleur.ajoutContact(contact);
			listeDisponibleModel.addElement(contact);
		}
	}//GEN-LAST:event_creerContactActionPerformed

	private void ajouterBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBoutonActionPerformed
		int indices[] = listExistant.getSelectedIndices();
		List<Contact> listeTemp = new LinkedList<Contact>();
		for (int i : indices) {
			Contact c = (Contact) listeDisponibleModel.get(i);
			listeTemp.add(c);
		}
		for (Contact c : listeTemp) {
			listeDisponibleModel.removeElement(c);
			listeAjouteeModel.addElement(c);
			listeContactsDisponible.remove(c);
			listeContactsAjoute.add(c);
		}
	}//GEN-LAST:event_ajouterBoutonActionPerformed

	private void retirerBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerBoutonActionPerformed
		int indices[] = listAjoutee.getSelectedIndices();
		List<Contact> listeTemp = new LinkedList<Contact>();
		for (int i : indices) {
			Contact c = (Contact) listeAjouteeModel.get(i);
			listeTemp.add(c);
		}
		for (Contact c : listeTemp) {
			listeDisponibleModel.addElement(c);
			listeAjouteeModel.removeElement(c);
			listeContactsDisponible.add(c);
			listeContactsAjoute.remove(c);
		}
	}//GEN-LAST:event_retirerBoutonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterBouton;
    private javax.swing.JButton creerContact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listAjoutee;
    private javax.swing.JList listExistant;
    private javax.swing.JButton retirerBouton;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables

	private List<Contact> listeContactsAjoute;
	private List<Contact> listeContactsDisponible;
	private Controleur controleur;

	private void initialisation() {
		listeContactsAjoute = new LinkedList<Contact>();
		controleur = Controleur.getInstance();
		listeContactsDisponible = controleur.getListeContacts();
		for (Contact c : listeContactsDisponible) {
			listeDisponibleModel.addElement(c);
		}
	}

	public List<Contact> showDialog() {
		initialisation();
		setVisible(true);
		return listeContactsAjoute;
	}

}
