/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogDate.java
 *
 * Created on 11 déc. 2009, 17:22:17
 */

package fr.alma.gtd.ihm.renseignement;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Le_Clubber
 */
public class DialogDate extends javax.swing.JDialog {

    /** Creates new form DialogDate */
    public DialogDate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
		setLocationRelativeTo(null);
        initComponents();
		initialisation();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labbelMois = new javax.swing.JLabel();
        comboMois = new javax.swing.JComboBox();
        labelAnnee = new javax.swing.JLabel();
        spinnerAnnee = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableauJour = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labbelMois.setText("Mois :");

        comboMois.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre" }));
        comboMois.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMoisItemStateChanged(evt);
            }
        });

        labelAnnee.setText("Année :");

        spinnerAnnee.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAnneeStateChanged(evt);
            }
        });

        tableauJour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableauJour.getTableHeader().setReorderingAllowed(false);
        tableauJour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableauJourMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableauJour);
        tableauJour.getColumnModel().getColumn(0).setResizable(false);
        tableauJour.getColumnModel().getColumn(1).setResizable(false);
        tableauJour.getColumnModel().getColumn(2).setResizable(false);
        tableauJour.getColumnModel().getColumn(3).setResizable(false);
        tableauJour.getColumnModel().getColumn(4).setResizable(false);
        tableauJour.getColumnModel().getColumn(5).setResizable(false);
        tableauJour.getColumnModel().getColumn(6).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labbelMois)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelAnnee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labbelMois)
                    .addComponent(comboMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnnee)
                    .addComponent(spinnerAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void tableauJourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableauJourMouseClicked
		int ligne = tableauJour.rowAtPoint(evt.getPoint());
		int colonne = tableauJour.columnAtPoint(evt.getPoint());
		Integer jour = (Integer) tableauJour.getValueAt(ligne, colonne);
		if (jour != null) {
			GregorianCalendar calendrierResultat = new GregorianCalendar();
			calendrierResultat.set((Integer)spinnerAnnee.getValue(), comboMois.getSelectedIndex(), jour);
			dateResultat = calendrierResultat.getTime();
		}
		dispose();
	}//GEN-LAST:event_tableauJourMouseClicked

	private void spinnerAnneeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAnneeStateChanged
		updateMatrice();
	}//GEN-LAST:event_spinnerAnneeStateChanged

	private void comboMoisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMoisItemStateChanged
		updateMatrice();
	}//GEN-LAST:event_comboMoisItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
		Date date = new DialogDate(new javax.swing.JFrame(), true).showDialog();
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		System.out.println(dateFormat.format(date));
		System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboMois;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labbelMois;
    private javax.swing.JLabel labelAnnee;
    private javax.swing.JSpinner spinnerAnnee;
    private javax.swing.JTable tableauJour;
    // End of variables declaration//GEN-END:variables

	Date dateResultat;

	private void initialisation() {
		dateResultat = null;
		GregorianCalendar cal = new GregorianCalendar();
		comboMois.setSelectedIndex(cal.get(Calendar.MONTH));
		spinnerAnnee.setValue(cal.get(Calendar.YEAR));

		// apparence selon le systeme
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
			javax.swing.SwingUtilities.updateComponentTreeUI(this);
		} catch (Exception e) {
			System.out.println("LookAndFeel non supporté.");
		}
	}

	private void updateMatrice() {
		GregorianCalendar cal = new GregorianCalendar((Integer)(spinnerAnnee.getValue()), comboMois.getSelectedIndex(), 1);
		//cal.setFirstDayOfWeek(Calendar.MONDAY);
		//efface le tableau
		for (int i=0; i<6; i++) {
			for (int j=0; j<7; j++) {
				tableauJour.setValueAt(null, i, j);
			}
		}
		//remplie le tableau
		int i = 0;
		int start = cal.get(Calendar.DAY_OF_WEEK);
		while (i<cal.getActualMaximum(Calendar.DAY_OF_MONTH)) {
			tableauJour.setValueAt(i+1, (i+start-1)/7, (i+start-1)%7);
			i++;
		}
	}
	
	public Date showDialog() {
		dateResultat = null;
		this.setVisible(true);
		return dateResultat;
	}

}
