
package fr.alma.gtd.ihm.renseignement;

import fr.alma.gtd.entities.Tache;
import fr.alma.gtd.ihm.Controleur;

public class DialogFaire extends javax.swing.JDialog {

    Tache tache;

    /** Creates new form DialogTache */
    public DialogFaire(java.awt.Frame parent, boolean modal,Tache tache) {
        super(parent, modal);
        this.tache = tache;
        initComponents();
		
		setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelAfficher = new fr.alma.gtd.ihm.renseignement.PanelAfficher(tache);
        annuler = new javax.swing.JButton();
        valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Création d'une nouvelle tâche");
        setName("Form"); // NOI18N

        panelAfficher.setName("panelAfficher"); // NOI18N

        annuler.setText("Annuler");
        annuler.setName("annuler"); // NOI18N
        annuler.addActionListener(new java.awt.event.ActionListener() {
			@Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        valider.setText("Tache terminée");
        valider.setName("valider"); // NOI18N
        valider.addActionListener(new java.awt.event.ActionListener() {
			@Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(valider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(annuler)
                .addContainerGap())
            .addComponent(panelAfficher, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelAfficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(annuler))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

	private void validerActionPerformed(java.awt.event.ActionEvent evt) {
		Controleur.getInstance().supprimerTache(tache);
		setVisible(false);
	}

	private void annulerActionPerformed(java.awt.event.ActionEvent evt) {
		setVisible(false);
	}

    // Variables declaration - do not modify
    private javax.swing.JButton annuler;
    private fr.alma.gtd.ihm.renseignement.PanelAfficher panelAfficher;
    private javax.swing.JButton valider;
    // End of variables declaration

}
