
package fr.alma.gtd.ihm.renseignement;

import fr.alma.gtd.entities.Element;

public class DialogTache extends javax.swing.JDialog {

    /** Creates new form DialogTache */
    public DialogTache(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
		infos = null;
        initComponents();
		panelRenseignement.compteCharge(true);
		panelRenseignement.actaliser();

		setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRenseignement = new fr.alma.gtd.ihm.renseignement.PanelRenseignement();
        annuler = new javax.swing.JButton();
        valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Création d'une nouvelle tâche");
        setName("Form"); // NOI18N

        panelRenseignement.setName("panelRenseignement"); // NOI18N

        annuler.setText("Annuler");
        annuler.setName("annuler"); // NOI18N
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed();
            }
        });

        valider.setText("Valider");
        valider.setName("valider"); // NOI18N
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(valider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(annuler)
                .addContainerGap())
            .addComponent(panelRenseignement, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelRenseignement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(annuler))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void validerActionPerformed() {//GEN-FIRST:event_validerActionPerformed
//		InfosRenseignement infosRenseignement = panelRenseignement.getRenseignements();
//		if (infosRenseignement.getNom().length() > 0) {
//			Controleur.getInstance().ajoutElement(infosRenseignement);
//			setVisible(false);
//		} else {
//			JOptionPane.showMessageDialog(null, "Veuiller renseigner le nom de la tâche", "Erreur", JOptionPane.ERROR_MESSAGE);
//		}
		infos = panelRenseignement.getRenseignements();
		setVisible(false);
	}//GEN-LAST:event_validerActionPerformed

	private void annulerActionPerformed() {//GEN-FIRST:event_annulerActionPerformed
		setVisible(false);
	}//GEN-LAST:event_annulerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private fr.alma.gtd.ihm.renseignement.PanelRenseignement panelRenseignement;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables

	private InfosRenseignement infos;

	public InfosRenseignement showDialog() {
		this.setVisible(true);
		return infos;
	}

	public void modifElement(Element infos) {
		panelRenseignement.setRenseignements(infos);
		this.setVisible(true);
	}

}
