/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelRenseignementTache.java
 *
 * Created on 27 nov. 2009, 05:02:16
 */

package fr.alma.gtd.ihm.renseignement;

import java.util.LinkedList;

/**
 *
 * @author E023963X
 */
public class PanelRenseignementTache extends javax.swing.JPanel {

	private LinkedList<String> listeLiens;
	private LinkedList<String> listeTag;

    /** Creates new form PanelRenseignementTache */
    public PanelRenseignementTache() {
        initComponents();
		listeLiens = new LinkedList<String>();
		listeTag = new LinkedList<String>();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPriorite = new javax.swing.JLabel();
        labelTauxEffort = new javax.swing.JLabel();
        labelLiens = new javax.swing.JLabel();
        labelTags = new javax.swing.JLabel();
        int min = 0;
        int max = 5; //il faut bien s'arreter quelque part!
        int step = 1;
        int initValue = 2;
        javax.swing.SpinnerModel model1 = new javax.swing.SpinnerNumberModel(initValue, min, max, step);
        spinnerPriorite = new javax.swing.JSpinner(model1);
        int max2 = 100;
        int initValue2 = 50;
        javax.swing.SpinnerModel model2 = new javax.swing.SpinnerNumberModel(initValue2, min, max2, step);
        spinnerTauxEffort = new javax.swing.JSpinner(model2);
        textLiens = new javax.swing.JTextField();
        textTags = new javax.swing.JTextField();
        ajouterLiens = new javax.swing.JButton();
        ajouterTags = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Renseignement d'une Tâche"));
        setName("Form"); // NOI18N

        labelPriorite.setText("Priorité :");
        labelPriorite.setName("labelPriorite"); // NOI18N

        labelTauxEffort.setText("Taux d'effort :");
        labelTauxEffort.setName("labelTauxEffort"); // NOI18N

        labelLiens.setText("Liens :");
        labelLiens.setName("labelLiens"); // NOI18N

        labelTags.setText("Tags :");
        labelTags.setName("labelTags"); // NOI18N

        spinnerPriorite.setName("spinnerPriorite"); // NOI18N

        spinnerTauxEffort.setName("spinnerTauxEffort"); // NOI18N

        textLiens.setName("textLiens"); // NOI18N
        textLiens.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textLiensCaretUpdate(evt);
            }
        });
        textLiens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLiensActionPerformed(evt);
            }
        });

        textTags.setName("textTags"); // NOI18N
        textTags.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textTagsCaretUpdate(evt);
            }
        });
        textTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTagsActionPerformed(evt);
            }
        });

        ajouterLiens.setText("Ajouter");
        ajouterLiens.setEnabled(false);
        ajouterLiens.setName("ajouterLiens"); // NOI18N
        ajouterLiens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterLiensActionPerformed(evt);
            }
        });

        ajouterTags.setText("Ajouter");
        ajouterTags.setEnabled(false);
        ajouterTags.setName("ajouterTags"); // NOI18N
        ajouterTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterTagsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTauxEffort)
                    .addComponent(labelPriorite)
                    .addComponent(labelLiens)
                    .addComponent(labelTags))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTags, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(textLiens, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerTauxEffort, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinnerPriorite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ajouterLiens)
                    .addComponent(ajouterTags))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPriorite)
                    .addComponent(spinnerPriorite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTauxEffort)
                    .addComponent(spinnerTauxEffort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLiens)
                    .addComponent(textLiens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterLiens))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTags)
                    .addComponent(textTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterTags))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void textLiensCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textLiensCaretUpdate
		ajouterLiens.setEnabled(textLiens.getText().length() > 0);
	}//GEN-LAST:event_textLiensCaretUpdate

	private void textLiensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLiensActionPerformed
		ajouterLien();
	}//GEN-LAST:event_textLiensActionPerformed

	private void ajouterLiensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterLiensActionPerformed
		ajouterLien();
	}//GEN-LAST:event_ajouterLiensActionPerformed

	private void textTagsCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textTagsCaretUpdate
		ajouterTags.setEnabled(textTags.getText().length()>0);
	}//GEN-LAST:event_textTagsCaretUpdate

	private void textTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTagsActionPerformed
		ajouterTag();
	}//GEN-LAST:event_textTagsActionPerformed

	private void ajouterTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterTagsActionPerformed
		ajouterTag();
	}//GEN-LAST:event_ajouterTagsActionPerformed

	private void ajouterLien() {
		listeLiens.add(textLiens.getText());
		textLiens.setText(null);
	}

	private void ajouterTag() {
		listeTag.add(textTags.getText());
		textTags.setText(null);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterLiens;
    private javax.swing.JButton ajouterTags;
    private javax.swing.JLabel labelLiens;
    private javax.swing.JLabel labelPriorite;
    private javax.swing.JLabel labelTags;
    private javax.swing.JLabel labelTauxEffort;
    private javax.swing.JSpinner spinnerPriorite;
    private javax.swing.JSpinner spinnerTauxEffort;
    private javax.swing.JTextField textLiens;
    private javax.swing.JTextField textTags;
    // End of variables declaration//GEN-END:variables

	public void compteCharge(boolean estCharge) {
		labelLiens.setEnabled(estCharge);
		labelPriorite.setEnabled(estCharge);
		labelTags.setEnabled(estCharge);
		labelTauxEffort.setEnabled(estCharge);
		spinnerPriorite.setEnabled(estCharge);
		spinnerTauxEffort.setEnabled(estCharge);
		textLiens.setEnabled(estCharge);
		textTags.setEnabled(estCharge);
	}

	public void actaliser() {
		// vider tous les champs
		spinnerPriorite.setValue(2);
		spinnerTauxEffort.setValue(50);
		textLiens.setText(null);
		textTags.setText(null);
	}

	public InfosTache getRenseignements() {
		InfosTache renseignements = new InfosTache((Integer) spinnerPriorite.getValue(), (Integer) spinnerTauxEffort.getValue(), listeLiens, listeTag);
		return renseignements;
	}

}
