
package fr.alma.gtd.ihm.renseignement;

public class PanelRenseignementProjet extends javax.swing.JPanel {

    /** Creates new form PanelRenseignementProjet */
    public PanelRenseignementProjet() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estOrdonneCheck = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Renseignement d'un projet"));
        setName("Form"); // NOI18N

        estOrdonneCheck.setText("Créer un projet dont les tâches sont dépendantes");
        estOrdonneCheck.setEnabled(false);
        estOrdonneCheck.setName("estOrdonneCheck"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estOrdonneCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estOrdonneCheck)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox estOrdonneCheck;
    // End of variables declaration//GEN-END:variables

	public void compteCharge(boolean estCharge) {
		estOrdonneCheck.setEnabled(estCharge);
	}

	public void actaliser() {
		// vider tous les champs
		estOrdonneCheck.setSelected(false);
	}

	public Boolean getRenseignements() {
		return estOrdonneCheck.isSelected();
	}

}
