package fr.alma.gtd.ihm.renseignement;

import fr.alma.gtd.entities.Contact;
import fr.alma.gtd.entities.Contexte;
import fr.alma.gtd.entities.Element;
import fr.alma.gtd.entities.Projet;
import fr.alma.gtd.ihm.Controleur;
import java.awt.CardLayout;
import java.util.LinkedList;
import java.util.List;

public class PanelRenseignement extends javax.swing.JPanel {

	private DialogContact dialogContact;
	private DialogEcheancier dialogEcheancier;

	/** Creates new form PanelRenseignement */
	public PanelRenseignement() {
		dialogContact = new DialogContact(null, true);
		dialogEcheancier = new DialogEcheancier(null, true);
		initComponents();
		initialisation();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        labelNom = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        labelDescription = new javax.swing.JLabel();
        scrollDescription = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();
        labelType = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox();
        labelContexte = new javax.swing.JLabel();
        comboContexte = new javax.swing.JComboBox();
        boutonContexte = new javax.swing.JButton();
        labelContacts = new javax.swing.JLabel();
        boutonContacts = new javax.swing.JButton();
        labelEcheancier = new javax.swing.JLabel();
        boutonEcheancier = new javax.swing.JButton();
        labelProjet = new javax.swing.JLabel();
        comboProjet = new javax.swing.JComboBox();
        boutonProjet = new javax.swing.JButton();
        panelDetail = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        panelGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("Renseignement général"));
        panelGeneral.setEnabled(false);
        panelGeneral.setName("panelGeneral"); // NOI18N

        labelNom.setText("Nom de l'élément :");
        labelNom.setName("labelNom"); // NOI18N

        textNom.setName("textNom"); // NOI18N

        labelDescription.setText("Description :");
        labelDescription.setName("labelDescription"); // NOI18N

        scrollDescription.setName("scrollDescription"); // NOI18N

        textDescription.setColumns(20);
        textDescription.setRows(5);
        textDescription.setName("textDescription"); // NOI18N
        scrollDescription.setViewportView(textDescription);

        labelType.setText("Type :");
        labelType.setName("labelType"); // NOI18N

        comboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tâche", "Projet" }));
        comboType.setName("comboType"); // NOI18N
        comboType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTypeItemStateChanged(evt);
            }
        });

        labelContexte.setText("Contexte :");
        labelContexte.setName("labelContexte"); // NOI18N

        comboContexte.setName("comboContexte"); // NOI18N

        boutonContexte.setText("Nouveau contexte...");
        boutonContexte.setName("boutonContexte"); // NOI18N
        boutonContexte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonContexteActionPerformed();
            }
        });

        labelContacts.setText("Contacts :");
        labelContacts.setName("labelContacts"); // NOI18N

        boutonContacts.setText("Gérer les contacts");
        boutonContacts.setName("boutonContacts"); // NOI18N
        boutonContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonContactsActionPerformed();
            }
        });

        labelEcheancier.setText("Echéancier :");
        labelEcheancier.setName("labelEcheancier"); // NOI18N

        boutonEcheancier.setText("Gérer l'échéancier");
        boutonEcheancier.setName("boutonEcheancier"); // NOI18N
        boutonEcheancier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEcheancierActionPerformed();
            }
        });

        labelProjet.setText("Projet parent :");
        labelProjet.setName("labelProjet"); // NOI18N

        comboProjet.setName("comboProjet"); // NOI18N

        boutonProjet.setText("Sélectionner...");
        boutonProjet.setName("boutonProjet"); // NOI18N
        boutonProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonProjetActionPerformed();
            }
        });

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNom)
                    .addComponent(labelDescription)
                    .addComponent(labelContexte)
                    .addComponent(labelProjet)
                    .addComponent(labelEcheancier)
                    .addComponent(labelContacts)
                    .addComponent(labelType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonContacts)
                    .addComponent(scrollDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(textNom, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                        .addComponent(comboContexte, 0, 135, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonContexte))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                        .addComponent(comboProjet, 0, 165, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonProjet))
                    .addComponent(boutonEcheancier))
                .addContainerGap())
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNom)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescription)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(scrollDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboContexte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContexte)
                    .addComponent(boutonContexte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProjet)
                    .addComponent(comboProjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonProjet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEcheancier)
                    .addComponent(boutonEcheancier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContacts)
                    .addComponent(boutonContacts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelType)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDetail.setEnabled(false);
        panelDetail.setName("panelDetail"); // NOI18N

        javax.swing.GroupLayout panelDetailLayout = new javax.swing.GroupLayout(panelDetail);
        panelDetail.setLayout(panelDetailLayout);
        panelDetailLayout.setHorizontalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        panelDetailLayout.setVerticalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void comboTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTypeItemStateChanged
		CardLayout cl = (CardLayout) (panelDetail.getLayout());
		cl.show(panelDetail, (String) evt.getItem());
	}//GEN-LAST:event_comboTypeItemStateChanged

	private void boutonContexteActionPerformed() {//GEN-FIRST:event_boutonContexteActionPerformed
		String contexte = new DialogAjoutContexte(null, true).showDialog();
		if (contexte != null) {
			Object selection = controleur.ajoutContexte(contexte);
			comboContexte.setSelectedItem(selection);
		}
	}//GEN-LAST:event_boutonContexteActionPerformed

	private void boutonProjetActionPerformed() {//GEN-FIRST:event_boutonProjetActionPerformed
		Projet selection = (Projet) new DialogSelectionProjet(null, true).showDialog();
		if (selection != null) {
			comboProjet.setSelectedItem(selection);
		}
	}//GEN-LAST:event_boutonProjetActionPerformed

	private void boutonEcheancierActionPerformed() {//GEN-FIRST:event_boutonEcheancierActionPerformed
		echeancier = dialogEcheancier.showDialog();
	}//GEN-LAST:event_boutonEcheancierActionPerformed

	private void boutonContactsActionPerformed() {//GEN-FIRST:event_boutonContactsActionPerformed
		contacts = dialogContact.showDialog();
	}//GEN-LAST:event_boutonContactsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonContacts;
    private javax.swing.JButton boutonContexte;
    private javax.swing.JButton boutonEcheancier;
    private javax.swing.JButton boutonProjet;
    private javax.swing.JComboBox comboContexte;
    private javax.swing.JComboBox comboProjet;
    private javax.swing.JComboBox comboType;
    private javax.swing.JLabel labelContacts;
    private javax.swing.JLabel labelContexte;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelEcheancier;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelProjet;
    private javax.swing.JLabel labelType;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JScrollPane scrollDescription;
    private javax.swing.JTextArea textDescription;
    private javax.swing.JTextField textNom;
    // End of variables declaration//GEN-END:variables

	private PanelRenseignementTache renseignementTache;
	private PanelRenseignementProjet renseignementProjet;
	private Controleur controleur;
	private InfosEcheancier echeancier;
	private List<Contact> contacts;

	private void initialisation() {
		renseignementTache = new PanelRenseignementTache();
		renseignementProjet = new PanelRenseignementProjet();
		CardLayout cardLayout = new CardLayout();
		panelDetail.setLayout(cardLayout);
		panelDetail.add("Tâche", renseignementTache);
		panelDetail.add("Projet", renseignementProjet);

		controleur = Controleur.getInstance();
		controleur.setPanelRenseignement(this);

		echeancier = new InfosEcheancier(Boolean.FALSE, null, null, null);
		contacts = new LinkedList<Contact>();
	}

	public void compteCharge(boolean estCharge) {
		labelNom.setEnabled(estCharge);
		textNom.setEnabled(estCharge);
		labelDescription.setEnabled(estCharge);
		textDescription.setEnabled(estCharge);
		labelType.setEnabled(estCharge);
		comboType.setEnabled(estCharge);

		renseignementTache.compteCharge(estCharge);
		renseignementProjet.compteCharge(estCharge);
	}

	public void actaliser() {
		// vider tous les champs
		textNom.setText(null);
		textDescription.setText(null);
		comboType.setSelectedIndex(0);

		renseignementTache.actaliser();
		renseignementProjet.actaliser();

		updateRenseignements();
	}

	public void setNomElement(String nom) {
		textNom.setText(nom);
	}

	public void updateRenseignements() {
		controleur.constructionComboContexte(comboContexte);
		controleur.constructionComboProjet(comboProjet);
	}

	public InfosRenseignement getRenseignements() {
		InfosRenseignement renseignements = null;
		if (comboType.getSelectedIndex() == 0) {
			InfosTache infos = renseignementTache.getRenseignements();
			renseignements = new InfosRenseignement(textNom.getText(), textDescription.getText(), (Contexte) comboContexte.getSelectedItem(),
					(Projet) comboProjet.getSelectedItem(), echeancier, contacts, Boolean.TRUE, infos.getPriorite(), infos.getTauxEffort());
		} else {
			renseignements = new InfosRenseignement(textNom.getText(), textDescription.getText(), (Contexte) comboContexte.getSelectedItem(),
					(Projet) comboProjet.getSelectedItem(), echeancier, contacts, Boolean.FALSE, renseignementProjet.getRenseignements());
		}
		return renseignements;
	}

	void setRenseignements(Element infos) {
		if (infos.estTache()) {
			comboType.setSelectedIndex(0);
		} else {
			comboType.setSelectedIndex(1);
		}
		comboType.setEnabled(false);
		textNom.setText(infos.getNom());
		textDescription.setText(infos.getNotes());
		comboContexte.setSelectedItem(infos.getContexte());
		comboProjet.setSelectedItem(infos.getProjetConteneur());
		//echeancier = infos.getEcheancier();
		contacts = (List<Contact>) infos.getContacts();
	}
}
