/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelAfficher.java
 *
 * Created on 21 janv. 2010, 21:59:13
 */

package fr.alma.gtd.ihm.renseignement;

import fr.alma.gtd.entities.Tache;

/**
 *
 * @author nicolasbremard
 */
public class PanelAfficher extends javax.swing.JPanel {

    Tache tache;

    /** Creates new form PanelAfficher */
    public PanelAfficher(Tache tache) {
        initComponents();
        this.tache = tache;
        initialisation();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        labelNom = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        labelDescription = new javax.swing.JLabel();
        scrollDescription = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();
        labelContexte = new javax.swing.JLabel();
        labelContacts = new javax.swing.JLabel();
        labelEcheancier = new javax.swing.JLabel();
        labelProjet = new javax.swing.JLabel();
        textContexte = new javax.swing.JTextField();
        textParent = new javax.swing.JTextField();
        textDebut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFrequence = new javax.swing.JTextField();
        textFin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textPriorite = new javax.swing.JTextField();
        textEffort = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textContacts = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textLiens = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textTags = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();

        panelGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("Renseignement général"));
        panelGeneral.setEnabled(false);

        labelNom.setText("Nom de l'élément :");

        labelDescription.setText("Description :");

        textDescription.setColumns(20);
        textDescription.setRows(5);
        scrollDescription.setViewportView(textDescription);

        labelContexte.setText("Contexte :");

        labelContacts.setText("Contacts :");

        labelEcheancier.setText("Echéancier :");

        labelProjet.setText("Projet parent :");

        textContexte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContexteActionPerformed();
            }
        });

        jLabel1.setText("Date de fin :");

        jLabel2.setText("Date de début :");

        jLabel3.setText("Fréquence : ");

        jLabel4.setText("Priorité :");

        jLabel5.setText("Taux d'effort : ");

        jLabel6.setText("Liens :");

        jLabel7.setText("Tags :");

        textPriorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrioriteActionPerformed();
            }
        });

        textContacts.setColumns(20);
        textContacts.setRows(5);
        jScrollPane1.setViewportView(textContacts);

        textLiens.setColumns(20);
        textLiens.setRows(5);
        jScrollPane2.setViewportView(textLiens);

        textTags.setColumns(20);
        textTags.setRows(5);
        jScrollPane3.setViewportView(textTags);


        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNom)
                    .addComponent(labelDescription)
                    .addComponent(labelProjet)
                    .addComponent(labelContexte)
                    .addComponent(labelEcheancier)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(labelContacts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(textNom, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(textParent, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(textContexte, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFrequence, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFin, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textPriorite, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEffort, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNom)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescription)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(scrollDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textContexte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContexte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProjet))
                .addGap(18, 18, 18)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEcheancier)
                    .addComponent(textDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFrequence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPriorite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEffort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContacts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textContexteActionPerformed() {//GEN-FIRST:event_textContexteActionPerformed
        
    }//GEN-LAST:event_textContexteActionPerformed

    private void textPrioriteActionPerformed() {//GEN-FIRST:event_textPrioriteActionPerformed
        
    }//GEN-LAST:event_textPrioriteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelContacts;
    private javax.swing.JLabel labelContexte;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelEcheancier;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelProjet;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JScrollPane scrollDescription;
    private javax.swing.JTextArea textContacts;
    private javax.swing.JTextField textContexte;
    private javax.swing.JTextField textDebut;
    private javax.swing.JTextArea textDescription;
    private javax.swing.JTextField textEffort;
    private javax.swing.JTextField textFin;
    private javax.swing.JTextField textFrequence;
    private javax.swing.JTextArea textLiens;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textParent;
    private javax.swing.JTextField textPriorite;
    private javax.swing.JTextArea textTags;
    // End of variables declaration//GEN-END:variables

    private void initialisation() {
        textNom.setText(tache.getNom());
        textNom.setEditable(false);
       
        textDescription.setText(tache.getNotes());
        textDescription.setEditable(false);

		String contacts = "";
//		Collection<Contact> listeContact = Controleur.getInstance().getContacts(tache);
//        if(!listeContact.isEmpty()){
//			for(Contact c : listeContact)
//				contacts += c.getNom()+"\n";
//        }
		textContacts.setText(contacts);
        textContacts.setEditable(false);

//        if(!tache.getLiens().isEmpty()){
        String liens = "";
//        for(String l : tache.getLiens())
//            liens += l +"\n";
        textLiens.setText(liens);
//        }
        textLiens.setEditable(false);

//        if(!tache.getTags().isEmpty()){
        String tags = "";
//        for(Tag t : tache.getTags())
//            tags += t.getNom() +"\n";
        textTags.setText(tags);
//        }
        textTags.setEditable(false);

        textContexte.setText(tache.getContexte().getNom());
        textContexte.setEditable(false);

        textParent.setText(tache.getProjetConteneur().getNom());
        textParent.setEditable(false);
        
        if(tache.getEcheancier()!=null){
        textDebut.setText(tache.getEcheancier().getDateDebut().toString());
        textFrequence.setText(tache.getEcheancier().getFrequence().name());
        textFin.setText(tache.getEcheancier().getDateArret().toString());
        }
        textDebut.setEditable(false);
        textFrequence.setEditable(false);
        textFin.setEditable(false);

        textPriorite.setText(tache.getPriorite().toString());
        textPriorite.setEditable(false);

        textEffort.setText(tache.getTauxEffort().toString());
        textEffort.setEditable(false);
    }

}
