package donneespartagees;


/**
 * donneespartagees/_serveurCORBAStub.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Ensemble des methodes disponibles pour les clients utilisant CORBA.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public class _serveurCORBAStub extends org.omg.CORBA.portable.ObjectImpl implements donneespartagees.serveurCORBA
{


	/**
	 * @param idee
	 * @param identification
	 * @param callback
	 */
	public void creerIdee (donneespartagees.IIdee idee, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("creerIdee", true);
			donneespartagees.IIdeeHelper.write ($out, idee);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			creerIdee (idee, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // creerIdee


	/**
	 * @param idee
	 * @param mode
	 * @param identification
	 * @param callback
	 */
	public void envoyerIdee (donneespartagees.IIdee idee, donneespartagees.ModeDeMiseAJour mode, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("envoyerIdee", true);
			donneespartagees.IIdeeHelper.write ($out, idee);
			donneespartagees.ModeDeMiseAJourHelper.write ($out, mode);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			envoyerIdee (idee, mode, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // envoyerIdee


	/**
	 * @param idee
	 * @param identification
	 * @param callback
	 */
	public void supprimerIdee (donneespartagees.IIdee idee, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("supprimerIdee", true);
			donneespartagees.IIdeeHelper.write ($out, idee);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			supprimerIdee (idee, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // supprimerIdee


	/**
	 * @param idee
	 * @param tache
	 * @param identification
	 * @param callback
	 */
	public void creerTache (donneespartagees.IIdee idee, donneespartagees.ITache tache, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("creerTache", true);
			donneespartagees.IIdeeHelper.write ($out, idee);
			donneespartagees.ITacheHelper.write ($out, tache);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			creerTache (idee, tache, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // creerTache


	/**
	 * @param tache
	 * @param mode
	 * @param identification
	 * @param callback
	 */
	public void envoyerTache (donneespartagees.ITache tache, donneespartagees.ModeDeMiseAJour mode, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("envoyerTache", true);
			donneespartagees.ITacheHelper.write ($out, tache);
			donneespartagees.ModeDeMiseAJourHelper.write ($out, mode);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			envoyerTache (tache, mode, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // envoyerTache


	/**
	 * @param tache
	 * @param identification
	 * @param callback
	 */
	public void supprimerTache (donneespartagees.ITache tache, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("supprimerTache", true);
			donneespartagees.ITacheHelper.write ($out, tache);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			supprimerTache (tache, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // supprimerTache


	/**
	 * @param idee
	 * @param projet
	 * @param identification
	 * @param callback
	 */
	public void creerProjet (donneespartagees.IIdee idee, donneespartagees.IProjet projet, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("creerProjet", true);
			donneespartagees.IIdeeHelper.write ($out, idee);
			donneespartagees.IProjetHelper.write ($out, projet);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			creerProjet (idee, projet, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // creerProjet


	/**
	 * @param projet
	 * @param mode
	 * @param identification
	 * @param callback
	 */
	public void envoyerProjet (donneespartagees.IProjet projet, donneespartagees.ModeDeMiseAJour mode, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("envoyerProjet", true);
			donneespartagees.IProjetHelper.write ($out, projet);
			donneespartagees.ModeDeMiseAJourHelper.write ($out, mode);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			envoyerProjet (projet, mode, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // envoyerProjet


	/**
	 * @param projet
	 * @param identification
	 * @param callback
	 */
	public void supprimerProjet (donneespartagees.IProjet projet, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("supprimerProjet", true);
			donneespartagees.IProjetHelper.write ($out, projet);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			supprimerProjet (projet, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // supprimerProjet


	/**
	 * @param contexte
	 * @param identification
	 * @param callback
	 * @throws RemoteException
	 */
	public void creerContexte (donneespartagees.IObjetServeur contexte, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("creerContexte", true);
			donneespartagees.IObjetServeurHelper.write ($out, contexte);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			creerContexte (contexte, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // creerContexte


	/**
	 * @param contexte
	 * @param mode
	 * @param identification
	 * @param callback
	 * @throws RemoteException
	 */
	public void envoyerContexte (donneespartagees.IObjetServeur contexte, donneespartagees.ModeDeMiseAJour mode, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("envoyerContexte", true);
			donneespartagees.IObjetServeurHelper.write ($out, contexte);
			donneespartagees.ModeDeMiseAJourHelper.write ($out, mode);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			envoyerContexte (contexte, mode, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // envoyerContexte


	/**
	 * @param contexte
	 * @param identification
	 * @param callback
	 * @throws RemoteException
	 */
	public void supprimerContexte (donneespartagees.IObjetServeur contexte, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("supprimerContexte", true);
			donneespartagees.IObjetServeurHelper.write ($out, contexte);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			supprimerContexte (contexte, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // supprimerContexte


	/**
	 * @param tag
	 * @param identification
	 * @param callback
	 * @throws RemoteException
	 */
	public void creerTag (donneespartagees.ITag tag, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("creerTag", true);
			donneespartagees.ITagHelper.write ($out, tag);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			creerTag (tag, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // creerTag


	/**
	 * @param tag
	 * @param mode
	 * @param identification
	 * @param callback
	 * @throws RemoteException
	 */
	public void envoyerTag (donneespartagees.ITag tag, donneespartagees.ModeDeMiseAJour mode, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("envoyerTag", true);
			donneespartagees.ITagHelper.write ($out, tag);
			donneespartagees.ModeDeMiseAJourHelper.write ($out, mode);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			envoyerTag (tag, mode, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // envoyerTag


	/**
	 * @param tag
	 * @param identification
	 * @param callback
	 * @throws RemoteException
	 */
	public void supprimerTag (donneespartagees.ITag tag, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("supprimerTag", true);
			donneespartagees.ITagHelper.write ($out, tag);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			supprimerTag (tag, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // supprimerTag


	/**
	 * @param contact
	 * @param identification
	 * @param callback
	 * @throws RemoteException
	 */
	public void creerContact (donneespartagees.IContact contact, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("creerContact", true);
			donneespartagees.IContactHelper.write ($out, contact);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			creerContact (contact, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // creerContact


	/**
	 * @param contact
	 * @param mode
	 * @param identification
	 * @param callback
	 * @throws RemoteException
	 */
	public void envoyerContact (donneespartagees.IContact contact, donneespartagees.ModeDeMiseAJour mode, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("envoyerContact", true);
			donneespartagees.IContactHelper.write ($out, contact);
			donneespartagees.ModeDeMiseAJourHelper.write ($out, mode);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			envoyerContact (contact, mode, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // envoyerContact


	/**
	 * @param contact
	 * @param identification
	 * @param callback
	 * @throws RemoteException
	 */
	public void supprimerContact (donneespartagees.IContact contact, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("supprimerContact", true);
			donneespartagees.IContactHelper.write ($out, contact);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			supprimerContact (contact, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // supprimerContact


	// ################################ METHODE DE MODIFICATION ################################
	public void ajouterTacheAProjet (donneespartagees.ITache tache, donneespartagees.IProjet projet, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("ajouterTacheAProjet", true);
			donneespartagees.ITacheHelper.write ($out, tache);
			donneespartagees.IProjetHelper.write ($out, projet);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			ajouterTacheAProjet (tache, projet, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // ajouterTacheAProjet

	public void retirerTacheDuProjet (donneespartagees.ITache tache, donneespartagees.IProjet projet, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("retirerTacheDuProjet", true);
			donneespartagees.ITacheHelper.write ($out, tache);
			donneespartagees.IProjetHelper.write ($out, projet);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			retirerTacheDuProjet (tache, projet, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // retirerTacheDuProjet

	public void ajouterParticipantAuProjet (donneespartagees.IProjet projet, donneespartagees.IParticipant nom, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("ajouterParticipantAuProjet", true);
			donneespartagees.IProjetHelper.write ($out, projet);
			donneespartagees.IParticipantHelper.write ($out, nom);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			ajouterParticipantAuProjet (projet, nom, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // ajouterParticipantAuProjet

	public void supprimerParticipantDuProjet (donneespartagees.IProjet projet, donneespartagees.IParticipant nom, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("supprimerParticipantDuProjet", true);
			donneespartagees.IProjetHelper.write ($out, projet);
			donneespartagees.IParticipantHelper.write ($out, nom);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			supprimerParticipantDuProjet (projet, nom, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // supprimerParticipantDuProjet

	public void ajouterParticipantDuProjetATache (donneespartagees.IProjet projet, donneespartagees.IParticipant nom, donneespartagees.ITache tache, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("ajouterParticipantDuProjetATache", true);
			donneespartagees.IProjetHelper.write ($out, projet);
			donneespartagees.IParticipantHelper.write ($out, nom);
			donneespartagees.ITacheHelper.write ($out, tache);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			ajouterParticipantDuProjetATache (projet, nom, tache, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // ajouterParticipantDuProjetATache

	public void retirerParticipantDeLaTache (donneespartagees.IParticipant nom, donneespartagees.ITache tache, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("retirerParticipantDeLaTache", true);
			donneespartagees.IParticipantHelper.write ($out, nom);
			donneespartagees.ITacheHelper.write ($out, tache);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			retirerParticipantDeLaTache (nom, tache, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // retirerParticipantDeLaTache


	// ################################ METHODE DE RECUPERATION ################################
	public void downloadInbox (String date, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadInbox", true);
			$out.write_string (date);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadInbox (date, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadInbox

	public void downloadInbox2 (String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadInbox2", true);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadInbox2 (identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadInbox2

	public void downloadPoubelle (String date, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadPoubelle", true);
			$out.write_string (date);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadPoubelle (date, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadPoubelle

	public void downloadPoubelle2 (String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadPoubelle2", true);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadPoubelle2 (identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadPoubelle2

	public void downloadArchive (String date, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadArchive", true);
			$out.write_string (date);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadArchive (date, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadArchive

	public void downloadArchive2 (String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadArchive2", true);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadArchive2 (identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadArchive2

	public void downloadProchainesTaches (String date, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadProchainesTaches", true);
			$out.write_string (date);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadProchainesTaches (date, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadProchainesTaches

	public void downloadProchainesTaches2 (String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadProchainesTaches2", true);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadProchainesTaches2 (identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadProchainesTaches2

	public void downloadProchainesTaches3 (donneespartagees.IObjetServeur contexte, String date, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadProchainesTaches3", true);
			donneespartagees.IObjetServeurHelper.write ($out, contexte);
			$out.write_string (date);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadProchainesTaches3 (contexte, date, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadProchainesTaches3

	public void downloadProchainesTaches4 (donneespartagees.IObjetServeur contexte, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadProchainesTaches4", true);
			donneespartagees.IObjetServeurHelper.write ($out, contexte);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadProchainesTaches4 (contexte, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadProchainesTaches4

	public void downloadCalendrier (String date, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadCalendrier", true);
			$out.write_string (date);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadCalendrier (date, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadCalendrier

	public void downloadCalendrier2 (String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadCalendrier2", true);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadCalendrier2 (identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadCalendrier2

	public void downloadTacheParTag (String date, donneespartagees.ITag tag, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadTacheParTag", true);
			$out.write_string (date);
			donneespartagees.ITagHelper.write ($out, tag);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadTacheParTag (date, tag, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadTacheParTag

	public void downloadTacheParTag2 (donneespartagees.ITag tag, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadTacheParTag2", true);
			donneespartagees.ITagHelper.write ($out, tag);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadTacheParTag2 (tag, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadTacheParTag2


	// ################################ METHODE DE GESTION DE COMPTE ################################
	public void creerCompte (String username, String password, String pseudo, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("creerCompte", true);
			$out.write_string (username);
			$out.write_string (password);
			$out.write_string (pseudo);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			creerCompte (username, password, pseudo, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // creerCompte

	public void supprimerCompte (String username, String password, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("supprimerCompte", true);
			$out.write_string (username);
			$out.write_string (password);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			supprimerCompte (username, password, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // supprimerCompte

	public void modifierPseudo (String pseudo, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("modifierPseudo", true);
			$out.write_string (pseudo);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			modifierPseudo (pseudo, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // modifierPseudo

	public void modifierUsername (String username, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("modifierUsername", true);
			$out.write_string (username);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			modifierUsername (username, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // modifierUsername

	public void modifierMotDePasse (String oldpPassword, String newPassword, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("modifierMotDePasse", true);
			$out.write_string (oldpPassword);
			$out.write_string (newPassword);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			modifierMotDePasse (oldpPassword, newPassword, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // modifierMotDePasse

	public void login (String username, String password, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
			$out.write_string (username);
			$out.write_string (password);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			login (username, password, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // login

	public void disconnect (String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("disconnect", true);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			disconnect (identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // disconnect

	public void downloadListeParticipant (String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadListeParticipant", true);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadListeParticipant (identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadListeParticipant

	public void downloadLog (String date, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadLog", true);
			$out.write_string (date);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadLog (date, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadLog

	public void downloadLog2 (String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadLog2", true);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadLog2 (identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadLog2


	// ################################ METHODE ADMINISTRATEUR ################################
	public void downloadLogAdmin (String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadLogAdmin", true);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadLogAdmin (identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadLogAdmin

	public void downloadInbox3 (String username, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadInbox3", true);
			$out.write_string (username);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadInbox3 (username, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadInbox3

	public void downloadTaches (String username, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadTaches", true);
			$out.write_string (username);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadTaches (username, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadTaches

	public void downloadProjets (String username, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadProjets", true);
			$out.write_string (username);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadProjets (username, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadProjets

	public void downloadLog3 (String username, String identification, donneespartagees.Callback callback)
	{
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request ("downloadLog3", true);
			$out.write_string (username);
			$out.write_string (identification);
			donneespartagees.CallbackHelper.write ($out, callback);
			$in = _invoke ($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream ();
			String _id = $ex.getId ();
			throw new org.omg.CORBA.MARSHAL (_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			downloadLog3 (username, identification, callback        );
		} finally {
			_releaseReply ($in);
		}
	} // downloadLog3

	// Type-specific CORBA::Object operations
	private static String[] __ids = {
	"IDL:donneespartagees/serveurCORBA:1.0"};

	@Override
	public String[] _ids ()
	{
		return (String[])__ids.clone ();
	}

	private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
	{
		String str = s.readUTF ();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
		org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
		_set_delegate (delegate);
	}

	private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
	{
		String[] args = null;
		java.util.Properties props = null;
		String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
		s.writeUTF (str);
	}
} // class _serveurCORBAStub
