package donneespartagees;

/**
 * donneespartagees/AvancementHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Enumeration representant les etats d'avancement possibles d'un projet ou d'une tache.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public final class AvancementHolder implements org.omg.CORBA.portable.Streamable
{
	public donneespartagees.Avancement value = null;

	public AvancementHolder ()
	{
	}

	public AvancementHolder (donneespartagees.Avancement initialValue)
	{
		value = initialValue;
	}

	public void _read (org.omg.CORBA.portable.InputStream i)
	{
		value = donneespartagees.AvancementHelper.read (i);
	}

	public void _write (org.omg.CORBA.portable.OutputStream o)
	{
		donneespartagees.AvancementHelper.write (o, value);
	}

	public org.omg.CORBA.TypeCode _type ()
	{
		return donneespartagees.AvancementHelper.type ();
	}

}
