package donneespartagees;


/**
 * donneespartagees/Avancement.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Enumeration representant les etats d'avancement possibles d'un projet ou d'une tache.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public class Avancement implements org.omg.CORBA.portable.IDLEntity
{
	private static final long serialVersionUID = 8507571171819931755L;
	private        int __value;
	private static int __size = 4;
	private static donneespartagees.Avancement[] __array = new donneespartagees.Avancement [__size];

	public static final int _AFAIRE = 0;
	public static final donneespartagees.Avancement AFAIRE = new donneespartagees.Avancement(_AFAIRE);
	public static final int _ENATTENTE = 1;
	public static final donneespartagees.Avancement ENATTENTE = new donneespartagees.Avancement(_ENATTENTE);
	public static final int _DELEGUE = 2;
	public static final donneespartagees.Avancement DELEGUE = new donneespartagees.Avancement(_DELEGUE);
	public static final int _TERMINE = 3;
	public static final donneespartagees.Avancement TERMINE = new donneespartagees.Avancement(_TERMINE);

	public int value ()
	{
		return __value;
	}

	public static donneespartagees.Avancement from_int (int value)
	{
		if (value >= 0 && value < __size)
			return __array[value];
		else
			throw new org.omg.CORBA.BAD_PARAM ();
	}

	protected Avancement (int value)
	{
		__value = value;
		__array[__value] = this;
	}
} // class Avancement
