package donneespartagees;


/**
 * donneespartagees/AvancementHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Enumeration representant les etats d'avancement possibles d'un projet ou d'une tache.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
abstract public class AvancementHelper
{
	private static String  _id = "IDL:donneespartagees/Avancement:1.0";

	public static void insert (org.omg.CORBA.Any a, donneespartagees.Avancement that)
	{
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
		a.type (type ());
		write (out, that);
		a.read_value (out.create_input_stream (), type ());
	}

	public static donneespartagees.Avancement extract (org.omg.CORBA.Any a)
	{
		return read (a.create_input_stream ());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;
	synchronized public static org.omg.CORBA.TypeCode type ()
	{
		if (__typeCode == null)
		{
			__typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (donneespartagees.AvancementHelper.id (), "Avancement", new String[] { "AFAIRE", "ENATTENTE", "DELEGUE", "TERMINE"} );
		}
		return __typeCode;
	}

	public static String id ()
	{
		return _id;
	}

	public static donneespartagees.Avancement read (org.omg.CORBA.portable.InputStream istream)
	{
		return donneespartagees.Avancement.from_int (istream.read_long ());
	}

	public static void write (org.omg.CORBA.portable.OutputStream ostream, donneespartagees.Avancement value)
	{
		ostream.write_long (value.value ());
	}

}
