package donneespartagees;


/**
 * donneespartagees/CallbackOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * L'interface de CallBack permettant au client de recevoir sa reponse.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public interface CallbackOperations 
{

	/**
	 * Methode appelee apres la reussite du traitement sur le serveur. 
	 * @param result Le resultat renvoye par le serveur.
	 */
	void onSucces (org.omg.CORBA.ObjectHolder result);

	/**
	 * Methode appelee apres l'echec du traitement sur le serveur.
	 * @throws L'exception renvoyee par le serveur.
	 */
	void onFailure (org.omg.CORBA.StringHolder message) throws donneespartagees.CallbackPackage.UneErreur;
} // interface CallbackOperations
