package donneespartagees;

/**
 * donneespartagees/FrequenceHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Enumeration representant les differentes frequences de repetition d'une tache possibles.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public final class FrequenceHolder implements org.omg.CORBA.portable.Streamable
{
	public donneespartagees.Frequence value = null;

	public FrequenceHolder ()
	{
	}

	public FrequenceHolder (donneespartagees.Frequence initialValue)
	{
		value = initialValue;
	}

	public void _read (org.omg.CORBA.portable.InputStream i)
	{
		value = donneespartagees.FrequenceHelper.read (i);
	}

	public void _write (org.omg.CORBA.portable.OutputStream o)
	{
		donneespartagees.FrequenceHelper.write (o, value);
	}

	public org.omg.CORBA.TypeCode _type ()
	{
		return donneespartagees.FrequenceHelper.type ();
	}

}
