package donneespartagees;


/**
 * donneespartagees/FrequenceHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Enumeration representant les differentes frequences de repetition d'une tache possibles.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
abstract public class FrequenceHelper
{
	private static String  _id = "IDL:donneespartagees/Frequence:1.0";

	public static void insert (org.omg.CORBA.Any a, donneespartagees.Frequence that)
	{
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
		a.type (type ());
		write (out, that);
		a.read_value (out.create_input_stream (), type ());
	}

	public static donneespartagees.Frequence extract (org.omg.CORBA.Any a)
	{
		return read (a.create_input_stream ());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;
	synchronized public static org.omg.CORBA.TypeCode type ()
	{
		if (__typeCode == null)
		{
			__typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (donneespartagees.FrequenceHelper.id (), "Frequence", new String[] { "JOURNALIER", "HEBDOMADAIRE", "MENSUEL", "ANNUEL"} );
		}
		return __typeCode;
	}

	public static String id ()
	{
		return _id;
	}

	public static donneespartagees.Frequence read (org.omg.CORBA.portable.InputStream istream)
	{
		return donneespartagees.Frequence.from_int (istream.read_long ());
	}

	public static void write (org.omg.CORBA.portable.OutputStream ostream, donneespartagees.Frequence value)
	{
		ostream.write_long (value.value ());
	}

}
