package donneespartagees;


/**
 * donneespartagees/Frequence.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Enumeration representant les differentes frequences de repetition d'une tache possibles.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public class Frequence implements org.omg.CORBA.portable.IDLEntity
{
	private static final long serialVersionUID = 8707683264383489282L;
	private        int __value;
	private static int __size = 4;
	private static donneespartagees.Frequence[] __array = new donneespartagees.Frequence [__size];

	public static final int _JOURNALIER = 0;
	public static final donneespartagees.Frequence JOURNALIER = new donneespartagees.Frequence(_JOURNALIER);
	public static final int _HEBDOMADAIRE = 1;
	public static final donneespartagees.Frequence HEBDOMADAIRE = new donneespartagees.Frequence(_HEBDOMADAIRE);
	public static final int _MENSUEL = 2;
	public static final donneespartagees.Frequence MENSUEL = new donneespartagees.Frequence(_MENSUEL);
	public static final int _ANNUEL = 3;
	public static final donneespartagees.Frequence ANNUEL = new donneespartagees.Frequence(_ANNUEL);

	public int value ()
	{
		return __value;
	}

	public static donneespartagees.Frequence from_int (int value)
	{
		if (value >= 0 && value < __size)
			return __array[value];
		else
			throw new org.omg.CORBA.BAD_PARAM ();
	}

	protected Frequence (int value)
	{
		__value = value;
		__array[__value] = this;
	}
} // class Frequence
