package donneespartagees;


/**
 * donneespartagees/IContactHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */

abstract public class IContactHelper
{
	private static String  _id = "IDL:donneespartagees/IContact:1.0";

	public static void insert (org.omg.CORBA.Any a, donneespartagees.IContact that)
	{
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
		a.type (type ());
		write (out, that);
		a.read_value (out.create_input_stream (), type ());
	}

	public static donneespartagees.IContact extract (org.omg.CORBA.Any a)
	{
		return read (a.create_input_stream ());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;
	synchronized public static org.omg.CORBA.TypeCode type ()
	{
		if (__typeCode == null)
		{
			__typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (donneespartagees.IContactHelper.id (), "IContact");
		}
		return __typeCode;
	}

	public static String id ()
	{
		return _id;
	}

	public static donneespartagees.IContact read (org.omg.CORBA.portable.InputStream istream)
	{
		return narrow (istream.read_Object (_IContactStub.class));
	}

	public static void write (org.omg.CORBA.portable.OutputStream ostream, donneespartagees.IContact value)
	{
		ostream.write_Object ((org.omg.CORBA.Object) value);
	}

	public static donneespartagees.IContact narrow (org.omg.CORBA.Object obj)
	{
		if (obj == null)
			return null;
		else if (obj instanceof donneespartagees.IContact)
			return (donneespartagees.IContact)obj;
		else if (!obj._is_a (id ()))
			throw new org.omg.CORBA.BAD_PARAM ();
		else
		{
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
			donneespartagees._IContactStub stub = new donneespartagees._IContactStub ();
			stub._set_delegate(delegate);
			return stub;
		}
	}

	public static donneespartagees.IContact unchecked_narrow (org.omg.CORBA.Object obj)
	{
		if (obj == null)
			return null;
		else if (obj instanceof donneespartagees.IContact)
			return (donneespartagees.IContact)obj;
		else
		{
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
			donneespartagees._IContactStub stub = new donneespartagees._IContactStub ();
			stub._set_delegate(delegate);
			return stub;
		}
	}

}
