package donneespartagees;

/**
 * donneespartagees/IContexteHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Interface representant les contextes d'une tache ou le contexte par defaut d'un projet.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public final class IContexteHolder implements org.omg.CORBA.portable.Streamable
{
	public donneespartagees.IContexte value = null;

	public IContexteHolder ()
	{
	}

	public IContexteHolder (donneespartagees.IContexte initialValue)
	{
		value = initialValue;
	}

	public void _read (org.omg.CORBA.portable.InputStream i)
	{
		value = donneespartagees.IContexteHelper.read (i);
	}

	public void _write (org.omg.CORBA.portable.OutputStream o)
	{
		donneespartagees.IContexteHelper.write (o, value);
	}

	public org.omg.CORBA.TypeCode _type ()
	{
		return donneespartagees.IContexteHelper.type ();
	}

}
