package donneespartagees;


/**
 * donneespartagees/IContact.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */

public interface IContact extends IContactOperations, donneespartagees.IObjetServeur, org.omg.CORBA.portable.IDLEntity 
{
} // interface IContact
