package donneespartagees;


/**
 * donneespartagees/IContexteOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Interface representant les contextes d'une tache ou le contexte par defaut d'un projet.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public interface IContexteOperations  extends donneespartagees.IObjetServeurOperations
{
	String Nom ();
	void Nom (String newNom);
	donneespartagees.IParticipant Createur ();
	void Createur (donneespartagees.IParticipant newCreateur);
} // interface IContexteOperations
