package donneespartagees;


/**
 * donneespartagees/IIdeeOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Interface representant les idees.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public interface IIdeeOperations  extends donneespartagees.IObjetServeurOperations
{
	String Nom ();
	void Nom (String newNom);
	String Description ();
	void Description (String newDescription);
	boolean DansLaPoubelle ();
	void DansLaPoubelle (boolean newDansLaPoubelle);
	donneespartagees.IParticipant Createur ();
	void Createur (donneespartagees.IParticipant newCreateur);

	/**
	 * Supprime l'id�e, en la mettant a la poubelle.
	 */
	void mettreALaPoubelle ();

	/**
	 * Restaurer la tache depuis la poubelle.
	 */
	void restaurer ();
} // interface IIdeeOperations
