package donneespartagees;


/**
 * donneespartagees/IObjetServeurOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Interface regroupant l'ensemble des comportements communs a tous les objets stockes sur le serveur.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public interface IObjetServeurOperations 
{
	String IdentifiantServeur ();
	void IdentifiantServeur (String newIdentifiantServeur);
	String DateDeDerniereModification ();
	void DateDeDerniereModification (String newDateDeDerniereModification);
} // interface IObjetServeurOperations
