package donneespartagees;


/**
 * donneespartagees/IParticipantOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Interface representant un participant.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public interface IParticipantOperations  extends donneespartagees.IObjetServeurOperations
{
	String Pseudonyme ();
	void Pseudonyme (String newPseudonyme);
} // interface IParticipantOperations
