package donneespartagees;


/**
 * donneespartagees/IProjetHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Interface representant les projets.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
abstract public class IProjetHelper
{
	private static String  _id = "IDL:donneespartagees/IProjet:1.0";

	public static void insert (org.omg.CORBA.Any a, donneespartagees.IProjet that)
	{
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
		a.type (type ());
		write (out, that);
		a.read_value (out.create_input_stream (), type ());
	}

	public static donneespartagees.IProjet extract (org.omg.CORBA.Any a)
	{
		return read (a.create_input_stream ());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;
	synchronized public static org.omg.CORBA.TypeCode type ()
	{
		if (__typeCode == null)
		{
			__typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (donneespartagees.IProjetHelper.id (), "IProjet");
		}
		return __typeCode;
	}

	public static String id ()
	{
		return _id;
	}

	public static donneespartagees.IProjet read (org.omg.CORBA.portable.InputStream istream)
	{
		return narrow (istream.read_Object (_IProjetStub.class));
	}

	public static void write (org.omg.CORBA.portable.OutputStream ostream, donneespartagees.IProjet value)
	{
		ostream.write_Object ((org.omg.CORBA.Object) value);
	}

	public static donneespartagees.IProjet narrow (org.omg.CORBA.Object obj)
	{
		if (obj == null)
			return null;
		else if (obj instanceof donneespartagees.IProjet)
			return (donneespartagees.IProjet)obj;
		else if (!obj._is_a (id ()))
			throw new org.omg.CORBA.BAD_PARAM ();
		else
		{
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
			donneespartagees._IProjetStub stub = new donneespartagees._IProjetStub ();
			stub._set_delegate(delegate);
			return stub;
		}
	}

	public static donneespartagees.IProjet unchecked_narrow (org.omg.CORBA.Object obj)
	{
		if (obj == null)
			return null;
		else if (obj instanceof donneespartagees.IProjet)
			return (donneespartagees.IProjet)obj;
		else
		{
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
			donneespartagees._IProjetStub stub = new donneespartagees._IProjetStub ();
			stub._set_delegate(delegate);
			return stub;
		}
	}

}
