package donneespartagees;


/**
 * donneespartagees/IProjetOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Interface representant les projets.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public interface IProjetOperations  extends donneespartagees.IObjetServeurOperations
{
	String Nom ();
	void Nom (String newNom);
	boolean EstDansPoubelle ();
	void EstDansPoubelle (boolean newEstDansPoubelle);
	donneespartagees.Avancement avancement ();
	void avancement (donneespartagees.Avancement newAvancement);
	donneespartagees.IContexte ContexteParDefaut ();
	void ContexteParDefaut (donneespartagees.IContexte newContexteParDefaut);
	donneespartagees.ITache[] ListeDeTaches ();
	void ListeDeTaches (donneespartagees.ITache[] newListeDeTaches);
	donneespartagees.IParticipant[] ListeDeParticipants ();
	void ListeDeParticipants (donneespartagees.IParticipant[] newListeDeParticipants);
	donneespartagees.IProjet[] ListeDeSousProjets ();
	void ListeDeSousProjets (donneespartagees.IProjet[] newListeDeSousProjets);
	donneespartagees.IParticipant Createur ();
	void Createur (donneespartagees.IParticipant newCreateur);
	donneespartagees.IContact[] ListeContacts ();
	void ListeContacts (donneespartagees.IContact[] newListeContacts);
	boolean DansArchive ();
	void DansArchive (boolean newDansArchive);

	/**
	 * Ajoute une tache au projet.
	 * @param t La tache a ajouter.
	 */
	void ajoutTache (donneespartagees.ITache t);

	/**
	 * Supprime la tache du projet.
	 * @param t La tache a supprimer.
	 */
	void supprimeTache (donneespartagees.ITache t);

	/**
	 * Supprime toutes les taches du projet.
	 */
	void supprimerToutesTaches ();

	/**
	 * Archive le projet.
	 */
	void archiver ();

	/**
	 * Supprime le projet, en le mettant a la poubelle.
	 */
	void mettreALaPoubelle ();

	/**
	 * Restaurer le projet depuis la poubelle.
	 */
	void restaurer ();
} // interface IProjetOperations
