package donneespartagees;


/**
 * donneespartagees/ITacheOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Interface representant les taches.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public interface ITacheOperations  extends donneespartagees.IObjetServeurOperations
{

	/**
	 * Archive la tache.
	 */
	void archiver ();

	/**
	 * Supprime la tache, en la mettant a la poubelle.
	 */
	void mettreALaPoubelle ();

	/**
	 * Restaurer la tache depuis la poubelle.
	 */
	void restaurer ();
	String Nom ();
	void Nom (String newNom);
	int Priorite ();
	void Priorite (int newPriorite);
	int TauxEffort ();
	void TauxEffort (int newTauxEffort);
	donneespartagees.Avancement avancement ();
	void avancement (donneespartagees.Avancement newAvancement);
	donneespartagees.Frequence frequence ();
	void frequence (donneespartagees.Frequence newFrequence);
	String DateDebut ();
	void DateDebut (String newDateDebut);
	String DateFin ();
	void DateFin (String newDateFin);
	boolean DansLaPoubelle ();
	void DansLaPoubelle (boolean newDansLaPoubelle);
	boolean DansArchive ();
	void DansArchive (boolean newDansArchive);
	donneespartagees.IParticipant Createur ();
	void Createur (donneespartagees.IParticipant newCreateur);
	donneespartagees.IParticipant Participant ();
	void Participant (donneespartagees.IParticipant newParticipant);
	donneespartagees.IContexte Contexte ();
	void Contexte (donneespartagees.IContexte newContexte);
	donneespartagees.ITag[] ListeDesTags ();
	void ListeDesTags (donneespartagees.ITag[] newListeDesTags);
	String[] ListeDesURLs ();
	void ListeDesURLs (String[] newListeDesURLs);
	donneespartagees.IProjet ProjetConteneur ();
	void ProjetConteneur (donneespartagees.IProjet newProjetConteneur);
	donneespartagees.ITache[] ListeTachesAnterieures ();
	void ListeTachesAnterieures (donneespartagees.ITache[] newListeTachesAnterieures);
	donneespartagees.IContact[] ListeContacts ();
	void ListeContacts (donneespartagees.IContact[] newListeContacts);
} // interface ITacheOperations
