package donneespartagees;


/**
 * donneespartagees/ITag.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Interface representant les tags.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public interface ITag extends ITagOperations, donneespartagees.IObjetServeur, org.omg.CORBA.portable.IDLEntity 
{
} // interface ITag
