package donneespartagees;


/**
 * donneespartagees/ModeDeMiseAJourHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Les differents modes de mise a jour des donnees sur le serveur.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
abstract public class ModeDeMiseAJourHelper
{
	private static String  _id = "IDL:donneespartagees/ModeDeMiseAJour:1.0";

	public static void insert (org.omg.CORBA.Any a, donneespartagees.ModeDeMiseAJour that)
	{
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
		a.type (type ());
		write (out, that);
		a.read_value (out.create_input_stream (), type ());
	}

	public static donneespartagees.ModeDeMiseAJour extract (org.omg.CORBA.Any a)
	{
		return read (a.create_input_stream ());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;
	synchronized public static org.omg.CORBA.TypeCode type ()
	{
		if (__typeCode == null)
		{
			__typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (donneespartagees.ModeDeMiseAJourHelper.id (), "ModeDeMiseAJour", new String[] { "FORCE", "WARNING"} );
		}
		return __typeCode;
	}

	public static String id ()
	{
		return _id;
	}

	public static donneespartagees.ModeDeMiseAJour read (org.omg.CORBA.portable.InputStream istream)
	{
		return donneespartagees.ModeDeMiseAJour.from_int (istream.read_long ());
	}

	public static void write (org.omg.CORBA.portable.OutputStream ostream, donneespartagees.ModeDeMiseAJour value)
	{
		ostream.write_long (value.value ());
	}

}
