package donneespartagees;

/**
 * donneespartagees/ModeDeMiseAJourHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Les differents modes de mise a jour des donnees sur le serveur.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public final class ModeDeMiseAJourHolder implements org.omg.CORBA.portable.Streamable
{
	public donneespartagees.ModeDeMiseAJour value = null;

	public ModeDeMiseAJourHolder ()
	{
	}

	public ModeDeMiseAJourHolder (donneespartagees.ModeDeMiseAJour initialValue)
	{
		value = initialValue;
	}

	public void _read (org.omg.CORBA.portable.InputStream i)
	{
		value = donneespartagees.ModeDeMiseAJourHelper.read (i);
	}

	public void _write (org.omg.CORBA.portable.OutputStream o)
	{
		donneespartagees.ModeDeMiseAJourHelper.write (o, value);
	}

	public org.omg.CORBA.TypeCode _type ()
	{
		return donneespartagees.ModeDeMiseAJourHelper.type ();
	}

}
