package donneespartagees;


/**
 * donneespartagees/ModeDeMiseAJour.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Les differents modes de mise a jour des donnees sur le serveur.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public class ModeDeMiseAJour implements org.omg.CORBA.portable.IDLEntity
{

	private static final long serialVersionUID = -8308773122119491812L;
	private        int __value;
	private static int __size = 2;
	private static donneespartagees.ModeDeMiseAJour[] __array = new donneespartagees.ModeDeMiseAJour [__size];

	public static final int _FORCE = 0;
	public static final donneespartagees.ModeDeMiseAJour FORCE = new donneespartagees.ModeDeMiseAJour(_FORCE);
	public static final int _WARNING = 1;
	public static final donneespartagees.ModeDeMiseAJour WARNING = new donneespartagees.ModeDeMiseAJour(_WARNING);

	public int value ()
	{
		return __value;
	}

	public static donneespartagees.ModeDeMiseAJour from_int (int value)
	{
		if (value >= 0 && value < __size)
			return __array[value];
		else
			throw new org.omg.CORBA.BAD_PARAM ();
	}

	protected ModeDeMiseAJour (int value)
	{
		__value = value;
		__array[__value] = this;
	}
} // class ModeDeMiseAJour
