package donneespartagees;


/**
 * donneespartagees/SequenceContactHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */

abstract public class SequenceContactHelper
{
	private static String  _id = "IDL:donneespartagees/SequenceContact:1.0";

	public static void insert (org.omg.CORBA.Any a, donneespartagees.IContact[] that)
	{
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
		a.type (type ());
		write (out, that);
		a.read_value (out.create_input_stream (), type ());
	}

	public static donneespartagees.IContact[] extract (org.omg.CORBA.Any a)
	{
		return read (a.create_input_stream ());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;
	synchronized public static org.omg.CORBA.TypeCode type ()
	{
		if (__typeCode == null)
		{
			__typeCode = donneespartagees.IContactHelper.type ();
			__typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
			__typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (donneespartagees.SequenceContactHelper.id (), "SequenceContact", __typeCode);
		}
		return __typeCode;
	}

	public static String id ()
	{
		return _id;
	}

	public static donneespartagees.IContact[] read (org.omg.CORBA.portable.InputStream istream)
	{
		donneespartagees.IContact value[] = null;
		int _len0 = istream.read_long ();
		value = new donneespartagees.IContact[_len0];
		for (int _o1 = 0;_o1 < value.length; ++_o1)
			value[_o1] = donneespartagees.IContactHelper.read (istream);
		return value;
	}

	public static void write (org.omg.CORBA.portable.OutputStream ostream, donneespartagees.IContact[] value)
	{
		ostream.write_long (value.length);
		for (int _i0 = 0;_i0 < value.length; ++_i0)
			donneespartagees.IContactHelper.write (ostream, value[_i0]);
	}

}
