package donneespartagees;


/**
 * donneespartagees/SequenceTacheHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */

public final class SequenceTacheHolder implements org.omg.CORBA.portable.Streamable
{
	public donneespartagees.ITache value[] = null;

	public SequenceTacheHolder ()
	{
	}

	public SequenceTacheHolder (donneespartagees.ITache[] initialValue)
	{
		value = initialValue;
	}

	public void _read (org.omg.CORBA.portable.InputStream i)
	{
		value = donneespartagees.SequenceTacheHelper.read (i);
	}

	public void _write (org.omg.CORBA.portable.OutputStream o)
	{
		donneespartagees.SequenceTacheHelper.write (o, value);
	}

	public org.omg.CORBA.TypeCode _type ()
	{
		return donneespartagees.SequenceTacheHelper.type ();
	}

}
