package donneespartagees;


/**
 * donneespartagees/SequenceProjetHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */

public final class SequenceProjetHolder implements org.omg.CORBA.portable.Streamable
{
	public donneespartagees.IProjet value[] = null;

	public SequenceProjetHolder ()
	{
	}

	public SequenceProjetHolder (donneespartagees.IProjet[] initialValue)
	{
		value = initialValue;
	}

	public void _read (org.omg.CORBA.portable.InputStream i)
	{
		value = donneespartagees.SequenceProjetHelper.read (i);
	}

	public void _write (org.omg.CORBA.portable.OutputStream o)
	{
		donneespartagees.SequenceProjetHelper.write (o, value);
	}

	public org.omg.CORBA.TypeCode _type ()
	{
		return donneespartagees.SequenceProjetHelper.type ();
	}

}
