package donneespartagees;


/**
 * donneespartagees/SequenceContexteHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */

public final class SequenceContexteHolder implements org.omg.CORBA.portable.Streamable
{
	public donneespartagees.IContexte value[] = null;

	public SequenceContexteHolder ()
	{
	}

	public SequenceContexteHolder (donneespartagees.IContexte[] initialValue)
	{
		value = initialValue;
	}

	public void _read (org.omg.CORBA.portable.InputStream i)
	{
		value = donneespartagees.SequenceContexteHelper.read (i);
	}

	public void _write (org.omg.CORBA.portable.OutputStream o)
	{
		donneespartagees.SequenceContexteHelper.write (o, value);
	}

	public org.omg.CORBA.TypeCode _type ()
	{
		return donneespartagees.SequenceContexteHelper.type ();
	}

}
