package donneespartagees;

/**
 * donneespartagees/serveurCORBAHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/Florian/workspace2/alma-gtd/idl/donneespartagees.idl
 * mercredi 6 janvier 2010 22 h 46 CET
 */


/**
 * Ensemble des methodes disponibles pour les clients utilisant CORBA.
 * @author Stephane Begaudeau, Benjamin Gosset, Alex Lagarde, Christophe Renaudineau.
 * @version 1.0.0
 */
public final class serveurCORBAHolder implements org.omg.CORBA.portable.Streamable
{
	public donneespartagees.serveurCORBA value = null;

	public serveurCORBAHolder ()
	{
	}

	public serveurCORBAHolder (donneespartagees.serveurCORBA initialValue)
	{
		value = initialValue;
	}

	public void _read (org.omg.CORBA.portable.InputStream i)
	{
		value = donneespartagees.serveurCORBAHelper.read (i);
	}

	public void _write (org.omg.CORBA.portable.OutputStream o)
	{
		donneespartagees.serveurCORBAHelper.write (o, value);
	}

	public org.omg.CORBA.TypeCode _type ()
	{
		return donneespartagees.serveurCORBAHelper.type ();
	}

}
